name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Check formatting with Prettier
      run: yarn format:check
    - name: Check quality with ESLint
      run: yarn lint
    - name: Check types compile
      run: yarn type-check
    - name: Check tests pass
      run: yarn test
    - name: Check app builds
      run: yarn build
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
          build: yarn run build
          start: yarn start